dbdata:
  image: postgres:9.3
  volumes:
    - /usr/local/var/postgres
  command: true

db:
  image: postgres:9.3
  volumes_from:
    - dbdata
  ports:
    - "5432"

web:
  build: .
  command: foreman start
  volumes:
    - /Users/jinpark/Documents/simpsons/videos:/myapp/public/videos
    - /Users/jinpark/Documents/simpsons/subtitles:/myapp/public/subtitles
  ports:
    - "5100:5100"
  links:
    - db
  environment:
    RAILS_ENV: production