dbdata:
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql
  command: true

db:
  image: postgres:9.3
  volumes_from:
    - dbdata
  ports:
    - "5432"

web:
  build: .
  command: foreman start
  volumes:
    - /Users/jinpark/Documents/simpsons/videos:/myapp/public/videos
    - /Users/jinpark/Documents/simpsons/subtitles:/myapp/public/subtitles
  ports:
    - "5100:5100"
  links:
    - db
  dns:
    - 8.8.8.8
  environment:
    RAILS_ENV: production
    SECRET_KEY_BASE: 632464e1060065bf5d4c01a72362e8e2baf565990cbbd973270de9744312f816561021abcfc445ac161c6b6767b4230262944c2fbccfd3f84bd0aeeb562d407a

nginx: 
  restart: always
  build: nginx/.
  command: 
  dns:
    - 8.8.8.8
  links:
    - web
  ports:
    - "80:80"  